# ------------------------------
# MineStore-Sync plugin by abhithedev
# Plugin version: v1.0
# ------------------------------



# ------------------------------
# MySQL Credentials
# ------------------------------
mysql:
  server_ip: "localhost:3306"
  username: "root"
  password: ""
  databasename: "minestore"